[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/customer"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/Admin_page/index.html"
  status = 200

[[redirects]]
  from = "/kitchen"
  to = "/kitchen.html"
  status = 200

[[redirects]]
  from = "/server"
  to = "/server.html"
  status = 200
